name: Deploy Botbot LeetCode

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and deploy to Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with: 
          go-version: '1.21.5'

      - name: Build binary for Lambda
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go
          zip deployment.zip bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name sending-leetcode-challenge --zip-file fileb://deployment.zip